version: "3"
services:
    app:
        container_name: server
        build: 
            dockerfile: Dockerfile_server
        ports:
            - "5000:5000"
        networks: 
            - default

    db:
        container_name: db
        build:
            dockerfile: Dockerfile_db
        image: mysql:8.0
        ports: 
            - "3306:3306"
        networks: 
            - default

networks:
    default: